apiVersion: v1
kind: Service
metadata:
  name: goodbye-world
  labels:
    app: goodbye-world
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: goodbye-world
