apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodbye-world
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: goodbye-world
          image: cp13dev/goodbye-world:latest
