apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-multiservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cp13-dev/gitops-fastapi-deployments'
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
